-- MySQL Script generated by MySQL Workbench
-- Sun Sep 30 21:13:05 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Treatments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Treatments` (
  `name` VARCHAR(255) NOT NULL,
  `number_of_days` INT(11) NULL,
  `number_of_days` INT(11) NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Diseases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Diseases` (
  `name` VARCHAR(255) NOT NULL,
  `severity` VARCHAR(255) NULL,
  `Treatments_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`name`, `Treatments_name`),
  INDEX `fk_Diseases_Treatments1_idx` (`Treatments_name` ASC) VISIBLE,
  CONSTRAINT `fk_Diseases_Treatments1`
    FOREIGN KEY (`Treatments_name`)
    REFERENCES `mydb`.`Treatments` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rooms` (
  `room_number` INT(11) NOT NULL,
  `type` VARCHAR(255) NULL,
  `floor_number` VARCHAR(255) NULL,
  PRIMARY KEY (`room_number`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Patients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Patients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fname` VARCHAR(255) NULL,
  `lname` VARCHAR(255) NULL,
  `phone_number` VARCHAR(255) NULL,
  `description` VARCHAR(255) NULL,
  `number_of_days` INT(11) NULL,
  `Diseases_name` VARCHAR(255) NOT NULL,
  `Rooms_room_number` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `Diseases_name`, `Rooms_room_number`),
  INDEX `fk_Patients_Diseases_idx` (`Diseases_name` ASC) VISIBLE,
  INDEX `fk_Patients_Rooms1_idx` (`Rooms_room_number` ASC) VISIBLE,
  CONSTRAINT `fk_Patients_Diseases`
    FOREIGN KEY (`Diseases_name`)
    REFERENCES `mydb`.`Diseases` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Patients_Rooms1`
    FOREIGN KEY (`Rooms_room_number`)
    REFERENCES `mydb`.`Rooms` (`room_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Doctors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Doctors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fname` VARCHAR(255) NULL,
  `lname` VARCHAR(255) NULL,
  `phone_number` VARCHAR(255) NULL,
  `speciality` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Nurses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Nurses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fname` VARCHAR(255) NULL,
  `lname` VARCHAR(255) NULL,
  `phone_number` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`WardBoys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`WardBoys` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fname` VARCHAR(255) NULL,
  `lname` VARCHAR(255) NULL,
  `phone_number` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Hospitals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Hospitals` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `address` VARCHAR(255) NULL,
  `phone_number` VARCHAR(255) NULL,
  `Patients_id` INT NOT NULL,
  `Patients_Diseases_name` VARCHAR(255) NOT NULL,
  `Patients_Rooms_room_number` INT(11) NOT NULL,
  `WardBoys_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Patients_id`, `Patients_Diseases_name`, `Patients_Rooms_room_number`, `WardBoys_id`),
  INDEX `fk_Hospitals_Patients1_idx` (`Patients_id` ASC, `Patients_Diseases_name` ASC, `Patients_Rooms_room_number` ASC) VISIBLE,
  INDEX `fk_Hospitals_WardBoys1_idx` (`WardBoys_id` ASC) VISIBLE,
  CONSTRAINT `fk_Hospitals_Patients1`
    FOREIGN KEY (`Patients_id` , `Patients_Diseases_name` , `Patients_Rooms_room_number`)
    REFERENCES `mydb`.`Patients` (`id` , `Diseases_name` , `Rooms_room_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Hospitals_WardBoys1`
    FOREIGN KEY (`WardBoys_id`)
    REFERENCES `mydb`.`WardBoys` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Patients_has_Nurses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Patients_has_Nurses` (
  `Patients_id` INT NOT NULL,
  `Patients_Diseases_name` VARCHAR(255) NOT NULL,
  `Patients_Doctors_id` INT NOT NULL,
  `Patients_Rooms_room_number` INT(11) NOT NULL,
  `Nurses_id` INT NOT NULL,
  PRIMARY KEY (`Patients_id`, `Patients_Diseases_name`, `Patients_Doctors_id`, `Patients_Rooms_room_number`, `Nurses_id`),
  INDEX `fk_Patients_has_Nurses_Nurses1_idx` (`Nurses_id` ASC) VISIBLE,
  INDEX `fk_Patients_has_Nurses_Patients1_idx` (`Patients_id` ASC, `Patients_Diseases_name` ASC, `Patients_Doctors_id` ASC, `Patients_Rooms_room_number` ASC) VISIBLE,
  CONSTRAINT `fk_Patients_has_Nurses_Patients1`
    FOREIGN KEY (`Patients_id` , `Patients_Diseases_name` , `Patients_Rooms_room_number`)
    REFERENCES `mydb`.`Patients` (`id` , `Diseases_name` , `Rooms_room_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Patients_has_Nurses_Nurses1`
    FOREIGN KEY (`Nurses_id`)
    REFERENCES `mydb`.`Nurses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`doc_treats_patients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`doc_treats_patients` (
  `Patients_id` INT NOT NULL,
  `Patients_Diseases_name` VARCHAR(255) NOT NULL,
  `Patients_Rooms_room_number` INT(11) NOT NULL,
  `Doctors_id` INT NOT NULL,
  PRIMARY KEY (`Patients_id`, `Patients_Diseases_name`, `Patients_Rooms_room_number`, `Doctors_id`),
  INDEX `fk_Patients_has_Doctors_Doctors1_idx` (`Doctors_id` ASC) VISIBLE,
  INDEX `fk_Patients_has_Doctors_Patients1_idx` (`Patients_id` ASC, `Patients_Diseases_name` ASC, `Patients_Rooms_room_number` ASC) VISIBLE,
  CONSTRAINT `fk_Patients_has_Doctors_Patients1`
    FOREIGN KEY (`Patients_id` , `Patients_Diseases_name` , `Patients_Rooms_room_number`)
    REFERENCES `mydb`.`Patients` (`id` , `Diseases_name` , `Rooms_room_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Patients_has_Doctors_Doctors1`
    FOREIGN KEY (`Doctors_id`)
    REFERENCES `mydb`.`Doctors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
