-- MySQL Script generated by MySQL Workbench
-- Tue Nov 13 20:52:36 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`admin` (
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`appointments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`appointments` (
  `appointment_no` INT(30) NOT NULL,
  `patient_id` INT(30) NOT NULL,
  `speciality` VARCHAR(30) NOT NULL,
  `medical_condition` TEXT NULL DEFAULT NULL,
  `doctors_suggestion` VARCHAR(30) NULL DEFAULT NULL,
  `payment_amount` INT(199) NULL DEFAULT NULL,
  `case_closed` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`appointment_no`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`clerks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clerks` (
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `fullname` VARCHAR(255) NOT NULL,
  `phonenumber` VARCHAR(255) NOT NULL,
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  PRIMARY KEY (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'stores information about clerk';


-- -----------------------------------------------------
-- Table `mydb`.`doctors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`doctors` (
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `fullname` VARCHAR(255) NOT NULL,
  `speciality` VARCHAR(255) NOT NULL,
  `phonenumber` VARCHAR(255) NOT NULL,
  `roomnumber` VARCHAR(255) NOT NULL,
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  PRIMARY KEY (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `fullname` VARCHAR(255) NOT NULL,
  `phonenumber` VARCHAR(255) NOT NULL,
  UNIQUE INDEX `username` (`email` ASC) VISIBLE,
  PRIMARY KEY (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`patient_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`patient_info` (
  `patient_Id` INT(20) NOT NULL,
  `full_name` VARCHAR(20) NOT NULL,
  `DOB` INT(10) NOT NULL,
  `weight` INT(8) NOT NULL,
  `phone_no` VARCHAR(30) NOT NULL,
  `address` VARCHAR(260) NOT NULL,
  `users_email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`patient_Id`, `users_email`),
  INDEX `fk_patient_info_users_idx` (`users_email` ASC) VISIBLE,
  CONSTRAINT `fk_patient_info_users`
    FOREIGN KEY (`users_email`)
    REFERENCES `mydb`.`users` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'patient';


-- -----------------------------------------------------
-- Table `mydb`.`patients_have_appointments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`patients_have_appointments` (
  `patient_Id` INT(20) NOT NULL,
  `users_email` VARCHAR(255) NOT NULL,
  `appointments_no` INT(30) NOT NULL,
  PRIMARY KEY (`patient_Id`, `users_email`, `appointments_no`),
  INDEX `fk_patient_info_has_appointments_appointments1_idx` (`appointments_no` ASC) VISIBLE,
  INDEX `fk_patient_info_has_appointments_patient_info1_idx` (`patient_Id` ASC, `users_email` ASC) VISIBLE,
  CONSTRAINT `fk_patient_info_has_appointments_patient_info1`
    FOREIGN KEY (`patient_Id` , `users_email`)
    REFERENCES `mydb`.`patient_info` (`patient_Id` , `users_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_patient_info_has_appointments_appointments1`
    FOREIGN KEY (`appointments_no`)
    REFERENCES `mydb`.`appointments` (`appointment_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Medical Center`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Medical Center` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  `address` VARCHAR(255) NULL,
  `phone_number` VARCHAR(255) NULL,
  `doctors_email` VARCHAR(255) NOT NULL,
  `users_email` VARCHAR(255) NOT NULL,
  `clerks_email` VARCHAR(255) NOT NULL,
  `admin_email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`doctors_email`, `users_email`, `clerks_email`, `admin_email`, `id`),
  INDEX `fk_Medical Center_users1_idx` (`users_email` ASC) VISIBLE,
  INDEX `fk_Medical Center_clerks1_idx` (`clerks_email` ASC) VISIBLE,
  INDEX `fk_Medical Center_admin1_idx` (`admin_email` ASC) VISIBLE,
  CONSTRAINT `fk_Medical Center_doctors1`
    FOREIGN KEY (`doctors_email`)
    REFERENCES `mydb`.`doctors` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Medical Center_users1`
    FOREIGN KEY (`users_email`)
    REFERENCES `mydb`.`users` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Medical Center_clerks1`
    FOREIGN KEY (`clerks_email`)
    REFERENCES `mydb`.`clerks` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Medical Center_admin1`
    FOREIGN KEY (`admin_email`)
    REFERENCES `mydb`.`admin` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
